### ISSUE TITLE
Eighth (bottom) function generator does not cycle

### ISSUE THREAD

**Issue by inscripttech** [denischevalier/StalysVCVPlugin#83]
When patching the end-of-cycle gate output of the eighth function generator into its own trigger input, it fails to cycle.

End-of-cycle gate output on the eighth function generator does not output gate-high even when that function is triggered externally.

Stalys v1.4.2 from VCV Library
VCV Rack v1.1.6

(edited for clarity)

**Comment by inscripttech** [comment]
Eighth function generator seems to be behaving as expected in a later session. Unsure of original cause.

**Comment by inscripttech** [comment]
Accidently closed without review. Apologies.

**Comment by denischevalier** [comment]
Thanks a lot for the bug report, I'll try to tackle it as soon as possible, but I have very little free time nowadays due to my real work.

**Comment by denischevalier** [comment]
Bug fixed with b0ce658
